version: "3.8"

services:
  openems_edge:
    image: openems/edge:latest
    container_name: openems_edge
    hostname: openems_edge
    restart: unless-stopped
    volumes:
      - openemsedge-conf:/config:rw
      - openemsedge-data:/data:rw
    ports:
      - 8080:8080

  openems_backend:
    image: openems/backend:latest
    container_name: openems_backend
    hostname: openems_backend
    restart: unless-stopped
    volumes:
      - openemsbackend-conf:/config:rw
      - openemsbackend-data:/data:rw
    ports:
      - 8079:8079

  openems_ui:
    image: openems/ui:latest
    container_name: openems_ui
    hostname: openems_ui
    restart: unless-stopped
    volumes:
      - openemsui-conf:/config:rw
      - openemsui-log:/log:rw
    ports:
      - 80:80

#  influxdb:
#    image: influxdb:alpine
#    container_name: influxdb
#    hostname: influxdb
#    restart: unless-stopped
#    volumes:
#      - influxdb:/var/lib/influxdb2:rw
#    ports:
#      - 8086:8086

volumes:
  openemsedge-conf:
  openemsedge-data:
  openemsbackend-conf:
  openemsbackend-data:
  openemsui-conf:
  openemsui-data:
#  influxdb: